import { describe, it } from 'vitest';
import * as fc from 'fast-check';
import {
    generateHeuristicFeedUrls,
    shouldProceedWithFeed,
} from '../../../domains/source-discovery/feed-extractor.service.js';

/**
 * Feature: ai-source-discovery
 *
 * Property 3: Heuristic feed URL generation
 * Validates: Requirements 3.4
 *
 * Property 4: Lọc kết quả LLM không đủ điều kiện
 * Validates: Requirements 3.3
 */

describe('feed-extractor.service — property tests', () => {
    /**
     * Property 3: Heuristic feed URL generation
     * Validates: Requirements 3.4
     *
     * For any valid website URL, all heuristic URLs generated by
     * generateHeuristicFeedUrls() SHALL be syntactically valid (parseable by new URL()).
     */
    it('Property 3: generateHeuristicFeedUrls — all generated URLs are parseable by new URL()', () => {
        fc.assert(
            fc.property(fc.webUrl(), (baseUrl) => {
                const heuristics = generateHeuristicFeedUrls(baseUrl);
                return heuristics.every((url) => {
                    try {
                        new URL(url);
                        return true;
                    } catch {
                        return false;
                    }
                });
            }),
            { numRuns: 100 }
        );
    });

    /**
     * Property 4: Lọc kết quả LLM không đủ điều kiện
     * Validates: Requirements 3.3
     *
     * For any extraction result with feedUrl = null or confidence = 'low',
     * shouldProceedWithFeed() SHALL return false.
     * Conversely, with a valid feedUrl and confidence 'medium' or 'high', SHALL return true.
     */
    it('Property 4: shouldProceedWithFeed — returns false for null feedUrl or low confidence, true otherwise', () => {
        fc.assert(
            fc.property(
                fc.record({
                    feedUrl: fc.option(fc.webUrl(), { nil: null }),
                    confidence: fc.constantFrom('low' as const, 'medium' as const, 'high' as const),
                }),
                (result) => {
                    const proceed = shouldProceedWithFeed(result);
                    if (result.feedUrl === null || result.confidence === 'low') {
                        return proceed === false;
                    }
                    return proceed === true;
                }
            ),
            { numRuns: 100 }
        );
    });
});
