#!/bin/bash

# Quick deployment commands cheat sheet

echo "📦 ocNewsBot - Quick Deploy Commands"
echo "======================================"
echo ""
echo "🚀 Initial Setup:"
echo "  1. Setup Docker Registry & GitHub Secrets (xem DEPLOYMENT.md)"
echo "  2. cp .env.production.example .env"
echo "  3. nano .env  # Cấu hình các biến môi trường"
echo "  4. ./deploy.sh latest"
echo ""
echo "🔄 Deploy Updates:"
echo "  ./deploy.sh latest          # Deploy bản latest"
echo "  ./deploy.sh main-abc123     # Deploy tag cụ thể"
echo ""
echo "📊 Monitoring:"
echo "  docker compose ps           # Xem trạng thái"
echo "  docker compose logs -f      # Xem logs realtime"
echo "  docker compose logs server  # Logs của server"
echo ""
echo "🔧 Maintenance:"
echo "  docker compose restart      # Restart services"
echo "  docker compose down         # Dừng services"
echo "  docker compose up -d        # Khởi động lại"
echo ""
echo "💾 Database:"
echo "  # Backup"
echo "  docker compose exec postgres pg_dump -U postgres rss_bot > backup.sql"
echo ""
echo "  # Restore"
echo "  cat backup.sql | docker compose exec -T postgres psql -U postgres rss_bot"
echo ""
echo "  # Migrations"
echo "  docker compose exec server npx prisma migrate deploy"
echo ""
echo "🧹 Cleanup:"
echo "  docker image prune -a -f    # Xóa images cũ"
echo "  docker volume prune -f      # Xóa volumes không dùng"
echo "  docker system prune -a -f   # Xóa tất cả (cẩn thận!)"
echo ""
echo "📚 Chi tiết: xem DEPLOYMENT.md"
