import { z } from 'zod';

export const createWorkspaceSchema = z.object({
    name: z.string().min(1, 'Workspace name cannot be empty').max(100),
    // slug is auto-generated by the service — not accepted from client
});

export const addMemberSchema = z.object({
    userId: z.number().int().positive('userId must be a positive integer'),
    role: z.enum(['OWNER', 'ADMIN', 'EDITOR', 'VIEWER']),
});

export type CreateWorkspaceInput = z.infer<typeof createWorkspaceSchema>;
export type AddMemberInput = z.infer<typeof addMemberSchema>;
